### ISSUE TITLE
Error - Create self-signed certificate

### ISSUE THREAD

**Issue by alzia** [jefffanjoy/DemoCode#1]
Running into an issue when creating self signed certificate -
**# Create self-signed certificate
Write-Output ("Creating self-signed certificate with expiration in '{0}' month(s)." -f $CertificateExpirationInMonths)
CreateSelfSignedCertificate -CertificateName $CertificateName -CertificatePassword $CertificatePassword -OutputFolder $CertificateOutputFolder -ExpirationInMonths $CertificateExpirationInMonths**

Which module are we missing for CreateSelfSignedCertificate?
**ERROR:**
CreateSelfSignedCertificate : The term 'CreateSelfSignedCertificate' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by jefffanjoy** [comment]
Is this for https://github.com/jefffanjoy/DemoCode/blob/master/Scripts/Azure%20Automation/RenewRunAsCertificate.ps1?  The function CreateSelfSignedCertificate resides right within the script so it should definitely be valid.

**Comment by alzia** [comment]
Yes, it was not a bug. I did not copy the function, thanks for your prompt reply :)
